name: RESTful API test workflow with Postman

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # workflow_dispatch:
  #     inputs:
  #       AWS_ACCESS_KEY_ID:
  #         description: "Access Key ID with Permissions to deploy IAM, and OIDC"
  #         required: true
  #       AWS_SECRET_ACCESS_KEY:
  #         description: "Secret Access Key with Permissions to deploy IAM, and OIDC"
  #         required: true
  #       AWS_REGION:
  #         description: "Region to deploy to."
  #         required: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Deploy Test Stack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'SampleStack'
          cdk_args: '--require-approval never --outputs-file cdk-output.json'
          working_dir: 'sample'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
      - name: Get API Endpoint
        run: |
          API_ENDPOINT=$(cat ./sample/cdk-output.json | jq -r '.SampleStack.APIEndpoint')
          echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
      - name: Run UI test with Newman
        env:
          API_ENDPOINT: ${{ env.API_ENDPOINT }}
        working-directory: ./sample
        run: |
          npm install -g newman
          npm install newman-reporter-html
          echo $API_ENDPOINT
          # run the postman collection with the API endpoint from environment variable
          npx newman run ./postman_collection.json -r cli,html --reporter-html-export ./newman_report.html --env-var "API_ENDPOINT=$API_ENDPOINT"
      - name: Tear Down Env
        user: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'destroy'
          cdk_stack: 'SampleStack'
          cdk_args: '--require-approval never'
          working_dir: 'sample'
          actions_comment: false
